name: CICD Assignment 2

on: 
    push:
        branches:
            - main

jobs:
   test:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Print the hello File
      run: |
        cat hello.txt
